services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - mapzilla-network
    environment:
      - AUTH_SECRET=7AQHbzL7cCTcUHpXvT5VHIZdCgJFEZwck24etrrwz60
      - NEXTAUTH_URL=http://localhost:3000
      - AUTH_KEYCLOAK_ID=mapzilla-rest-api
      - AUTH_KEYCLOAK_SECRET=**********
      - AUTH_KEYCLOAK_ISSUER=http://keycloak:8080/realms/Mapzilla

    develop:
      watch:
        - action: sync
          path: ./
          target: /app/
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json


networks:
  mapzilla-network:
    name: mapzilla-network