import { Navbar } from '@/app/core/navbar';
import '@/app/globals.css';
import SessionProviderWrapper from '@/app/homepage/context/SessionProviderWrapper';
import TanstackProvider from '@/components/providers/tanstack-provider';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
// import { AuthProvider } from "./context/AuthProvider";

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SessionProviderWrapper>
          <TanstackProvider>
            <Navbar />
            {children}
          </TanstackProvider>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
